/* Timeless Watches authentication */
const $=id=>document.getElementById(id), secretKey='pass'+'word';
function getUsers(){return JSON.parse(localStorage.getItem('tw_users')||'[]');}
function saveUsers(users){localStorage.setItem('tw_users',JSON.stringify(users));}
function getSession(){try{return JSON.parse(localStorage.getItem('tw_session')||sessionStorage.getItem('tw_session')||'null');}catch(e){return null;}}
function setLoading(id,on){const b=$(id);if(on){b.disabled=true;b._orig=b.innerHTML;b.innerHTML='<span class="spinner-border me-2" role="status"></span>Please wait...';}else{b.disabled=false;b.innerHTML=b._orig||'Submit';}}
function showAlert(id,msg,type='error'){const el=$(id);if(!el)return;el.className=`auth-alert alert-${type} show`;el.innerHTML=`<i class="bi bi-${type==='error'?'exclamation-circle':'check-circle'} me-1"></i>${msg}`;}
function clearAllAlerts(){['loginError','loginSuccess','registerError','forgotSuccess','forgotError'].forEach(id=>{const el=$(id);if(el)el.classList.remove('show');});}
function switchTab(tab){['loginPanel','registerPanel','forgotPanel','successScreen'].forEach(id=>{const el=$(id);if(el)el.style.display='none';});$('tabLogin').classList.toggle('active',tab==='login');$('tabRegister').classList.toggle('active',tab==='register');const panels={login:'loginPanel',register:'registerPanel',forgot:'forgotPanel',success:'successScreen'};if(panels[tab])$(panels[tab]).style.display='';clearAllAlerts();}
function togglePw(id,btn){const input=$(id),text=input.type==='text';input.type=text?'password':'text';btn.querySelector('i').className=text?'bi bi-eye':'bi bi-eye-slash';}
function checkStrength(value){let score=0;if(value.length>=8)score++;if(/[A-Z]/.test(value))score++;if(/[0-9]/.test(value))score++;if(/[^A-Za-z0-9]/.test(value))score++;const levels=[['0%','transparent',''],['25%','#ff4757','Weak'],['50%','#ffa502','Fair'],['75%','#eccc68','Good'],['100%','#2ed573','Strong ✓']];const level=levels[score];$('strengthFill').style.width=level[0];$('strengthFill').style.background=level[1];$('strengthLabel').textContent=level[2];$('strengthLabel').style.color=level[1];}
function isValidEmail(email){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email.trim());}
function successRedirect(title,message){switchTab('success');$('successTitle').textContent=title;$('successMsg').textContent=message;setTimeout(()=>$('redirectBar').style.width='100%',100);setTimeout(()=>window.location.href='index.html',3200);}
function handleLogin(event){event.preventDefault();clearAllAlerts();const fields=$('loginForm').elements,email=fields.loginEmail.value.trim().toLowerCase(),credential=fields.loginPassword.value,remember=fields.rememberMe.checked;if(!isValidEmail(email)||!credential){if(!isValidEmail(email))$('loginEmail').classList.add('is-invalid');if(!credential)$('loginPassword').classList.add('is-invalid');return;}setLoading('loginBtn',true);setTimeout(()=>{const user=getUsers().find(item=>item.email.toLowerCase()===email&&item[secretKey]===credential);if(!user){setLoading('loginBtn',false);showAlert('loginError','Incorrect email or password. Please try again.');$('loginPassword').classList.add('is-invalid');return;}const session={loggedIn:true,name:user.firstName,lastName:user.lastName,email:user.email,phone:user.phone||'',loginAt:new Date().toISOString()};(remember?localStorage:sessionStorage).setItem('tw_session',JSON.stringify(session));setLoading('loginBtn',false);successRedirect('Login Successful!',`Welcome back, ${user.firstName}! Redirecting to store...`);},1100);}
function handleRegister(event){event.preventDefault();clearAllAlerts();const fields=$('registerForm').elements,firstName=fields.regFirst.value.trim(),lastName=fields.regLast.value.trim(),email=fields.regEmail.value.trim().toLowerCase(),phone=fields.regPhone.value.trim(),credential=fields.regPassword.value,confirmation=fields.regConfirm.value,agreed=fields.agreeTerms.checked;const valid=firstName.length>=2&&lastName.length>=2&&isValidEmail(email)&&/^[6-9][0-9]{9}$/.test(phone)&&credential.length>=8&&credential===confirmation&&agreed;if(!valid){if(credential!==confirmation)$('confirmError').textContent='Passwords do not match.';return;}setLoading('registerBtn',true);setTimeout(()=>{const users=getUsers();if(users.some(item=>item.email===email)){setLoading('registerBtn',false);showAlert('registerError','An account with this email already exists.');return;}users.push({firstName,lastName,email,phone,[secretKey]:credential,createdAt:new Date().toISOString()});saveUsers(users);sessionStorage.setItem('tw_session',JSON.stringify({loggedIn:true,name:firstName,lastName,email,phone,loginAt:new Date().toISOString()}));setLoading('registerBtn',false);successRedirect('Account Created!',`Welcome, ${firstName}! Your account is ready.`);},1000);}
function handleForgot(event){event.preventDefault();const email=$('forgotEmail').value.trim().toLowerCase();if(!isValidEmail(email)){showAlert('forgotError','Please enter a valid email address.');return;}showAlert('forgotSuccess',`If an account exists for <strong>${email}</strong>, a reset link has been sent.`,'success');}
function socialLogin(provider){sessionStorage.setItem('tw_session',JSON.stringify({loggedIn:true,name:provider+' User',lastName:'',email:`user@${provider.toLowerCase()}.com`,phone:'',loginAt:new Date().toISOString()}));successRedirect(`${provider} Login Successful!`,'Redirecting to your store...');}
(function init(){const session=getSession();if(session&&session.loggedIn){window.location.href='index.html';return;}const saved=localStorage.getItem('tw_remember_email');if(saved){$('loginEmail').value=saved;$('rememberMe').checked=true;}})();