/* Timeless Watches authentication */
const $ = id => document.getElementById(id);
function getUsers() { return JSON.parse(localStorage.getItem('tw_users') || '[]'); }
function saveUsers(arr) { localStorage.setItem('tw_users', JSON.stringify(arr)); }
function getSession() { try { return JSON.parse(localStorage.getItem('tw_session') || sessionStorage.getItem('tw_session') || 'null'); } catch(e) { return null; } }
function setLoading(btnId, on, original) { const btn=$(btnId); if(on){btn.disabled=true;btn._orig=btn.innerHTML;btn.innerHTML='<span class="spinner-border me-2" role="status"></span>Please wait...';}else{btn.disabled=false;btn.innerHTML=btn._orig||original||'Submit';} }
function showAlert(id,msg,type='error'){const el=$(id);el.className=`auth-alert alert-${type} show`;el.innerHTML=`<i class="bi bi-${type==='error'?'exclamation-circle':'check-circle'} me-1"></i>${msg}`;}
function hideAlert(id){const el=$(id);el.classList.remove('show');}
function clearAllAlerts(){['loginError','loginSuccess','registerError','forgotSuccess','forgotError'].forEach(id=>{const el=$(id);if(el)el.classList.remove('show');});}
function switchTab(tab){['loginPanel','registerPanel','forgotPanel','successScreen'].forEach(id=>{const el=$(id);if(el)el.style.display='none';});$('tabLogin').classList.toggle('active',tab==='login');$('tabRegister').classList.toggle('active',tab==='register');const panels={login:'loginPanel',register:'registerPanel',forgot:'forgotPanel',success:'successScreen'};if(panels[tab])$(panels[tab]).style.display='';clearAllAlerts();}
function togglePw(inputId,btn){const inp=$(inputId);const isText=inp.type==='text';inp.type=isText?'password':'text';btn.querySelector('i').className=isText?'bi bi-eye':'bi bi-eye-slash';}
function checkStrength(val){let score=0;if(val.length>=8)score++;if(/[A-Z]/.test(val))score++;if(/[0-9]/.test(val))score++;if(/[^A-Za-z0-9]/.test(val))score++;const levels=[{w:'0%',c:'transparent',l:''},{w:'25%',c:'#ff4757',l:'Weak'},{w:'50%',c:'#ffa502',l:'Fair'},{w:'75%',c:'#eccc68',l:'Good'},{w:'100%',c:'#2ed573',l:'Strong ✓'}];const lv=levels[score];$('strengthFill').style.width=lv.w;$('strengthFill').style.background=lv.c;$('strengthLabel').textContent=lv.l;$('strengthLabel').style.color=lv.c;}
function isValidEmail(email){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email.trim());}
function successRedirect(title,msg){switchTab('success');$('successTitle').textContent=title;$('successMsg').textContent=msg;setTimeout(()=>$('redirectBar').style.width='100%',100);setTimeout(()=>window.location.href='index.html',3200);}
function handleLogin(e){e.preventDefault();clearAllAlerts();const email=$('loginEmail').value.trim().toLowerCase(),pass=$('loginPassword').value,remember=$('rememberMe').checked;let valid=true;if(!isValidEmail(email)){$('loginEmail').classList.add('is-invalid');valid=false;}else $('loginEmail').classList.remove('is-invalid');if(!pass){$('loginPassword').classList.add('is-invalid');valid=false;}else $('loginPassword').classList.remove('is-invalid');if(!valid)return;setLoading('loginBtn',true);setTimeout(()=>{const user=getUsers().find(u=>u.email.toLowerCase()===email&&u.password===pass);if(!user){setLoading('loginBtn',false);showAlert('loginError','Incorrect email or password. Please try again.');$('loginPassword').classList.add('is-invalid');return;}const session={loggedIn:true,name:user.firstName,lastName:user.lastName,email:user.email,phone:user.phone||'',loginAt:new Date().toISOString()};(remember?localStorage:sessionStorage).setItem('tw_session',JSON.stringify(session));setLoading('loginBtn',false);successRedirect('Login Successful!',`Welcome back, ${user.firstName}! Redirecting to store...`);},1100);}
function handleRegister(e){e.preventDefault();clearAllAlerts();const first=$('regFirstName').value.trim(),last=$('regLastName').value.trim(),email=$('regEmail').value.trim().toLowerCase(),phone=$('regPhone').value.trim(),pass=$('regPassword').value,confirm=$('regConfirmPassword').value;let valid=true;[['regFirstName',first],['regLastName',last],['regEmail',email],['regPhone',phone],['regPassword',pass],['regConfirmPassword',confirm]].forEach(([id,value])=>$(id).classList.toggle('is-invalid',!value));if(!isValidEmail(email)){ $('regEmail').classList.add('is-invalid'); valid=false; }if(!/^[6-9]\d{9}$/.test(phone)){ $('regPhone').classList.add('is-invalid'); valid=false; }if(pass.length<8){ $('regPassword').classList.add('is-invalid'); valid=false; }if(pass!==confirm){ $('regConfirmPassword').classList.add('is-invalid'); valid=false; }if(!valid)return;const users=getUsers();if(users.some(u=>u.email===email)){showAlert('registerError','An account with this email already exists.');return;}users.push({firstName:first,lastName:last,email,phone,password:pass,createdAt:new Date().toISOString()});saveUsers(users);$('regForm').reset();showAlert('registerError','Account created successfully. You can now sign in.','success');switchTab('login');}
function handleForgot(e){e.preventDefault();const email=$('forgotEmail').value.trim().toLowerCase();if(!isValidEmail(email)){showAlert('forgotError','Please enter a valid email address.');return;}showAlert('forgotSuccess','Password reset instructions have been sent in this demo.','success');}
function socialLogin(provider){const session={loggedIn:true,name:provider+' User',lastName:'',email:`user@${provider.toLowerCase()}.com`,phone:'',loginAt:new Date().toISOString()};sessionStorage.setItem('tw_session',JSON.stringify(session));successRedirect(`${provider} Login Successful!`,'Redirecting to your store...');}
(function init(){const sess=getSession();if(sess&&sess.loggedIn){window.location.href='index.html';return;}const saved=localStorage.getItem('tw_remember_email');if(saved){$('loginEmail').value=saved;$('rememberMe').checked=true;}})();
