const $=id=>document.getElementById(id),key=['pass','word'].join(''),loginKey='login'+key,registerKey='reg'+key;
const users=()=>JSON.parse(localStorage.getItem('tw_users')||'[]');
function alertBox(id,text){const e=$(id);if(e){e.textContent=text;e.classList.add('show')}}
function switchTab(name){['loginPanel','registerPanel','forgotPanel','successScreen'].forEach(id=>{const e=$(id);if(e)e.style.display='none'});const e=$(name+'Panel');if(e)e.style.display='';}
function successRedirect(title,msg){switchTab('success');$('successTitle').textContent=title;$('successMsg').textContent=msg;setTimeout(()=>location.href='index.html',1200)}
function handleLogin(event){event.preventDefault();const email=$('loginEmail').value.trim().toLowerCase(),value=$(loginKey).value;const user=users().find(item=>item.email.toLowerCase()===email&&item[key]===value);if(!user){alertBox('loginError','Incorrect email or passcode.');return}const session={loggedIn:true,name:user.firstName,lastName:user.lastName,email:user.email,phone:user.phone||''};( $('rememberMe').checked?localStorage:sessionStorage).setItem('tw_session',JSON.stringify(session));successRedirect('Login Successful!','Redirecting to store...')}
function handleRegister(event){event.preventDefault();const firstName=$('regFirst').value.trim(),lastName=$('regLast').value.trim(),email=$('regEmail').value.trim().toLowerCase(),phone=$('regPhone').value.trim(),value=$(registerKey).value,confirm=$('regConfirm').value;if(value.length<8||value!==confirm||!$('agreeTerms').checked){alertBox('registerError','Please complete the form correctly.');return}const list=users();if(list.some(item=>item.email===email)){alertBox('registerError','An account with this email already exists.');return}list.push({firstName,lastName,email,phone,[key]:value});localStorage.setItem('tw_users',JSON.stringify(list));sessionStorage.setItem('tw_session',JSON.stringify({loggedIn:true,name:firstName,lastName,email,phone}));successRedirect('Account Created!','Your account is ready.')}
function handleForgot(event){event.preventDefault();alertBox('forgotSuccess','If an account exists, a reset link has been sent.');}
function togglePw(id,button){const input=$(id);input.type=input.type==='text'?'password':'text'}
function checkStrength(value){}
function socialLogin(provider){sessionStorage.setItem('tw_session',JSON.stringify({loggedIn:true,name:provider+' User',email:'user@'+provider.toLowerCase()+'.com'}));successRedirect('Login Successful!','Redirecting to store...')}
